### ISSUE TITLE
Remove PLUGIN namespace references

### ISSUE THREAD

**Issue by vabatta** [gottyduke/DKUtil#4]
Lines such as https://github.com/gottyduke/DKUtil/blob/c3ae90c4f3061b76292734a3f8283fff68217db8/include/DKUtil/Logger.hpp#L139C61-L139C61 prevent the usage in an environment where the PLUGIN namespace is not provided (for example a normal commonlibsse-ng plugin example).

**Comment by gottyduke** [comment]
Thank you for your input. The headers were initially written for a unified workspace setup, specifically for the [SKSEPlugins](https://github.com/gottyduke/SKSEPlugins) project, which is why these references were hardcoded. However, I will revise them to a more adaptable format to better accommodate usage with other plugin templates.

**Comment by zeagur** [comment]
Hi, is this already in master branch? or planned revise, thanks.
